### ISSUE TITLE
check vue.js

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-lab#3]
Review how can we:
 - [x] Communicate with another service
 - [x] Bind components in UI
 - [x] Communicate web client/service
 - [x] Interactive layout
 - [x] Add threejs
 - [x] Add a workbench: Not very nice.
 - [x] Dynamic styling

**Comment by mguidon** [comment]
Add a Readme with review

**Comment by odeimaiz** [comment]
Review:
https://github.com/ITISFoundation/oSPARC_Test/blob/master/demos/frontend-vue/Review.md

**Comment by pcrespov** [comment]
@odeimaiz  we need to put this into a docker and create a makefile as agreed in [new rules](https://github.com/ITISFoundation/osparc-lab/blob/master/demos/README.md)
