### ISSUE TITLE
check react.js

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-lab#4]
Review how can we:
 - [x] Communicate with another service
 - [x] Bind components in UI
 - [x] Communicate web client/service
 - [x] Interactive layout
 - [x] Add threejs
 - [x] Add a workbench
 - [x] Dynamic styling

**Comment by mguidon** [comment]
- will add a workbench so client can add a pipeline

**Comment by odeimaiz** [comment]
Review:
https://github.com/ITISFoundation/oSPARC_Test/blob/master/demos/frontend-react/Review.md

**Comment by pcrespov** [comment]
Some of this functionality was merge in #19

**Comment by pcrespov** [comment]
@odeimaiz : I added a makefile for the demo. Shouln't we close this one? What is still missing?

**Comment by odeimaiz** [comment]
@pcrespov  We need to fix the socket.io issue before closing it.

**Comment by pcrespov** [comment]
Please create a bug ticket for that, review the doc/rules and close if applies.thx
